# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb4fb007b19336950034306656b06114202867369fc3c90bc27204c1a8c78059061f1243e8d33f0231f2dc9d5c4c97cd0e76ae6a5ee171dff9bccae20441c155

test:
  secret_key_base: 300d27be62850fc8afb83a832fe7f93f8af86203c45bbc6997b871f380939eb0fc548c3a057863c0fc39f69c55e391b931b1aee3187ecdb916a9e68307757ede

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
